service: psycopg2-lambda-layer

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  profile: 788845836002
  stage: dev

layers:
  psycopg2-py38:
    description: "psycopg2 python postgresql client library."
    buildScript: ./build.sh
    path: layer
    compatibleRuntimes:
      - python3.8
    allowedAccounts:
      - '*'
    retain: true
